### ISSUE TITLE
Input signal should be passed only in process() function

### ISSUE THREAD

**Issue by josebeo2016** [josebeo2016/audio_preprocess#3]
In the DeNoise module, input_signal is passed into the constructor `__init__()`. However, it should be put in `process()` to call the constructor once in initializing phase only.
Please fix that code @nguyenvulong

**Comment by nguyenvulong** [comment]
done https://github.com/josebeo2016/audio_preprocess/commit/f908d4959223bf7cd27e3ddce4b98e0c582d5679#diff-d962a1363c63222fff587af4aa52f4a46b3ce9d51b01f947f28c5c6f41ca1ebb
